[package]
name = "gym-clock"
version = "0.1.0"
authors = ["spruc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.6"
